version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: medboard_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"

  backend:
    container_name: medboard_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app # Mount local backend folder for live reload
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

volumes:
  postgres_data: